name: Build and Release

on:
  push:
    tags:
      - 'v*.*' 

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: pril-editor-linux
            asset_name: pril-editor-linux.tar.gz
          - os: macos-latest
            artifact_name: pril-editor-macos
            asset_name: pril-editor-macos.zip
          - os: windows-latest
            artifact_name: pril-editor.exe
            asset_name: pril-editor-windows.zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSYS2 for Windows
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          make

    - name: Build the application
      shell: msys2 {0}
      run: make

    - name: Package the artifact
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          7z a ${{ matrix.asset_name }} ${{ matrix.artifact_name }}
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          zip ${{ matrix.asset_name }} ${{ matrix.artifact_name }}
        else
          tar -czvf ${{ matrix.asset_name }} ${{ matrix.artifact_name }}
        fi

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${{ matrix.asset_name }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
