name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: pril-editor
            asset_name: pril-editor-linux.tar.gz
            package_cmd: tar -czf
            shell_type: bash
            build_dir: .
          - os: macos-latest
            artifact_name: pril-editor
            asset_name: pril-editor-macos.zip
            package_cmd: zip
            shell_type: bash
            build_dir: .
          - os: windows-latest
            artifact_name: pril-editor.exe
            asset_name: pril-editor-windows.zip
            package_cmd: 7z a
            shell_type: msys2 {0}
            build_dir: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install wxWidgets (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwxgtk3.2-dev build-essential

      - name: Install wxWidgets (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install wxwidgets
          # Ensure wx-config is in PATH (usually is)
          echo "wx-config: $(wx-config --version)"

      - name: Setup MSYS2 + wxWidgets (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-wxwidgets
            make

      - name: Build executable
        shell: ${{ matrix.shell_type }}
        run: |
          make
          # Verify the binary was created
          ls -l ${{ matrix.artifact_name }} || exit 1

      - name: Package executable
        run: |
          ${{ matrix.package_cmd }} "${{ matrix.asset_name }}" "${{ matrix.artifact_name }}"
        shell: bash

      - name: Upload Release Asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream

      - name: Upload Artifact (Manual Run)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}
